[install]
state = enabled
build = 1
install_source_checksum = 10ee4a292bc4fbb0febc410a3103ba1546799739

[ui]
is_visible = true
is_manageable = false
label = OpenCTI Threat Match Dashboard

[launcher]
author = Your Team
description = OpenCTI IOC matching dashboards, searches, and alerts (Zeek-ready)
version = 0.1.0
