[opencti_domains_kv]

[opencti_ips_kv]

[opencti_urls_kv]

[opencti_hashes_kv]

[opencti_emails_kv]

[opencti_seenbefore_kv]

[threatfeed_current_domain_kv]

[threatfeed_current_ip_kv]

[threatfeed_current_url_kv]

[threatfeed_current_hash_kv]

[threatfeed_current_email_kv]

[opencti_tm_monitored_indexs_and_fields]
