[opencti_seenbefore_mark_malicious_domain]
label = OpenCTI: Mark Domain as Malicious
type = search
eventtypes = *
fields = domain,match_value
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="domain", ioc_rating="malicious", decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_mark_benign_domain]
label = OpenCTI: Mark Domain as Benign
type = search
eventtypes = *
fields = domain,match_value
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="domain", ioc_rating="benign", decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_clear_domain]
label = OpenCTI: Clear Domain SeenBefore
type = search
eventtypes = *
fields = domain,match_value
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="domain", ioc_rating="unreviewed", decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_mark_malicious_ip]
label = OpenCTI: Mark IP as Malicious
type = search
eventtypes = *
fields = ip
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="ip", ioc_rating="malicious", decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_mark_benign_ip]
label = OpenCTI: Mark IP as Benign
type = search
eventtypes = *
fields = ip
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="ip", ioc_rating="benign", decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_clear_ip]
label = OpenCTI: Clear IP SeenBefore
type = search
eventtypes = *
fields = ip
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="ip", ioc_rating="unreviewed", decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true
