[opencti_seenbefore_mark_malicious_domain]
label = OpenCTI: Mark Domain as Malicious
type = search
eventtypes = *
fields = domain,match_value
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="domain", ioc_rating="malicious", cleared=0, decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_mark_benign_domain]
label = OpenCTI: Mark Domain as Benign
type = search
eventtypes = *
fields = domain,match_value
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="domain", ioc_rating="benign", cleared=0, decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_mark_cleared_domain]
label = OpenCTI: Mark Domain as Cleared
type = search
eventtypes = *
fields = domain,match_value
search.search_string = | inputlookup opencti_seenbefore_kv | search indicator="$@field_value$" type="domain" | append [ | makeresults count=1 | eval indicator="$@field_value$", type="domain", ioc_rating="unreviewed", cleared=0, note="" ] | head 1 | eval cleared=1, decided_at=now(), decided_by="$env:user$", _key=md5(type."|".indicator) | fields _key indicator type ioc_rating cleared decided_at decided_by note | outputlookup kvcoll://opencti_seenbefore_kv

[opencti_seenbefore_clear_domain]
label = OpenCTI: Clear Domain SeenBefore
type = search
eventtypes = *
fields = domain,match_value
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="domain", ioc_rating="unreviewed", cleared=0, decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_mark_malicious_ip]
label = OpenCTI: Mark IP as Malicious
type = search
eventtypes = *
fields = ip
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="ip", ioc_rating="malicious", cleared=0, decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_mark_benign_ip]
label = OpenCTI: Mark IP as Benign
type = search
eventtypes = *
fields = ip
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="ip", ioc_rating="benign", cleared=0, decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true

[opencti_seenbefore_mark_cleared_ip]
label = OpenCTI: Mark IP as Cleared
type = search
eventtypes = *
fields = ip
search.search_string = | inputlookup opencti_seenbefore_kv | search indicator="$@field_value$" type="ip" | append [ | makeresults count=1 | eval indicator="$@field_value$", type="ip", ioc_rating="unreviewed", cleared=0, note="" ] | head 1 | eval cleared=1, decided_at=now(), decided_by="$env:user$", _key=md5(type."|".indicator) | fields _key indicator type ioc_rating cleared decided_at decided_by note | outputlookup kvcoll://opencti_seenbefore_kv

[opencti_seenbefore_clear_ip]
label = OpenCTI: Clear IP SeenBefore
type = search
eventtypes = *
fields = ip
search.search_string = | makeresults count=1 | eval indicator="$@field_value$", type="ip", ioc_rating="unreviewed", cleared=0, decided_at=now(), decided_by="$env:user$" | eval _key=md5(type."|".indicator) | outputlookup kvcoll://opencti_seenbefore_kv append=true
